<?php 

namespace App\Modelos;

class SearchViewDefault{
    
    static function add($param){

        $content = "<?php\n";
        $content .= "\n";
        $content .= "use OpenEMR\Core\Header;\n";
        $content .= "\n";
        $content .= "Header::setupHeader(['datatables', 'datatables-colreorder', 'datatables-dt']);\n";
        $content .= "\n";
        $content .= "\$listener = \$this->listenerObject; \n";
        $content .= "\$res = \$this->view;\n";
        $content .= "\$form = \$this->form;\n";
        $content .= "\$isForm = \$this->isForm; \n";
        $content .= "\$form->setAttribute('action', \$this->url('{$param}', ['action' => 'search']));\n";
        $content .= "\$form->prepare();\n";
        $content .= "\$submit = \$form->get('submit');\n";
        $content .= "\$submit->setAttribute('class', 'btn btn-secondary btn-save');\n";
        $content .= "\n";
        $content .= "if(\$isForm == 0){ \n";
        $content .= "    echo \$this->form()->openTag(\$form);\n";
        $content .= "    \$form->get('oxigenoterapia')->setValue(1);\n";
        $content .= "    \$form->get('residente_status')->setValue(1);\n";
        $content .= "    \$title = \$listener->z_xlt('Buscar {$param}'); ?>\n";
        $content .= "\n";
        $content .= "    <div id=\"printtable p-4\">\n";
        $content .= "        <div class=\"se_in_16\">\n";
        $content .= "            <h3><?= \$this->escapeHtml(\$title) ?></h3>\n";
        $content .= "            <table>\n";
        $content .= "                <tr>\n";
        $content .= "                    <td class=\"text data text-right\"><label><?=\$listener->z_xlt('Nombre del residente:'); ?></label></td>\n";
        $content .= "                    <td>\n";
        $content .= "                        <?=\$this->formRow(\$form->get('fname'));?>\n";
        $content .= "                    </td>\n";
        $content .= "                </tr>\n";
        $content .= "                <tr>\n";
        $content .= "                    <td class=\"text data text-right\"><label><?=\$listener->z_xlt('Apellidos del residente:'); ?></label></td>\n";
        $content .= "                    <td>\n";
        $content .= "                        <?=\$this->formRow(\$form->get('lname'));?>\n";
        $content .= "                    </td>\n";
        $content .= "                </tr>\n";
        $content .= "                <tr>\n";
        $content .= "                    <td class=\"text data text-right\"><label><?=\$listener->z_xlt('Desde:'); ?></label></td>\n";
        $content .= "                    <td>\n";
        $content .= "                        <?=\$this->formRow(\$form->get('fechaInicioI'));?>\n";
        $content .= "                    </td>\n";
        $content .= "                </tr>\n";
        $content .= "                <tr>\n";
        $content .= "                    <td class=\"text data text-right\"><label><?=\$listener->z_xlt('Hasta:'); ?></label></td>\n";
        $content .= "                    <td>\n";
        $content .= "                        <?=\$this->formRow(\$form->get('fechaFinI'));?>\n";
        $content .= "                    </td>\n";
        $content .= "                </tr>\n";
        $content .= "                <tr>\n";
        $content .= "                    <td class=\"text data text-right\"><label><?=\$listener->z_xlt('Residentes Status:'); ?></label></td>\n";
        $content .= "                    <td>\n";
        $content .= "                        <?=\$this->formRow(\$form->get('residente_status'));?>\n";
        $content .= "                    </td>\n";
        $content .= "                </tr>\n";
        $content .= "                <tr>\n";
        $content .= "                    <td></td>\n";
        $content .= "                    <td>\n";
        $content .= "                        <?=\$this->formSubmit(\$submit)?>\n";
        $content .= "                    </td>\n";
        $content .= "                </tr>\n";
        $content .= "            </table>\n";
        $content .= "        </div>\n";
        $content .= "    </div>\n";
        $content .= "    <div class=\"modal\" id=\"modal\" tabindex=\"-1\" aria-hidden=\"true\" data-backdrop=\"static\">\n";
        $content .= "        <div class=\"modal-dialog modal-dialog-centered\" role=\"document\" style=\"width: 120px; height: 120px;\">\n";
        $content .= "            <span class=\"loader\"></span>\n";
        $content .= "        </div>\n";
        $content .= "    </div>\n";
        $content .= "    <div class=\"clear\"></div>\n";
        $content .= "    \n";
        $content .= "    <?php echo \$this->form()->closeTag();\n";
        $content .= "\n";
        $content .= "} else {\n";
        $content .= "    \$title = \$listener->z_xlt('Listado de {$param}');\n";
        $content .= "    \$this->headTitle(\$title); ?>\n";
        $content .= "\n";
        $content .= "    <div id=\"printtable\">\n";
        $content .= "        <div class=\"se_in_16\">\n";
        $content .= "            <h3 class=\"py-3\"><?= \$this->escapeHtml(\$title) ?></h3>\n";
        $content .= "            <table class=\"table table-sm table-hover\" id=\"{strtolower($param)}\">\n";
        $content .= "                <thead class=\"thead-primary\">\n";
        $content .= "                    <tr>\n";
        $content .= "                        <th class=\"text-center\" style=\"width: 300px;\"><small><?=\$listener->z_xlt('Residentes')?></small></th>\n";
        $content .= "                    </tr>\n";
        $content .= "                </thead>\n";
        $content .= "                <?php \n";
        $content .= "                \$i = 0;\n";
        $content .= "                foreach (\${strtolower($param)} as \$residentes) : \n";
        $content .= "                    if(\$i != \$residentes['pid']){ ?>\n";
        $content .= "                        <tr class=\"table-secondary\">\n";
        $content .= "                            <td class=\"text-center align-middle\"><small><?= \$this->escapeHtml(\$residentes['fname']).\" \".\$this->escapeHtml(\$residentes['lname']) ?></small></td>\n";
        $content .= "                            \n";
        $content .= "                        </tr>\n";
        $content .= "                        <?php\n";
        $content .= "                        \$i = \$residentes['pid'];\n";
        $content .= "                    }\n";
        $content .= "                endforeach; ?>\n";
        $content .= "            </table>\n";
        $content .= "        </div>\n";
        $content .= "    </div>\n";
        $content .= "    <script>\n";
        $content .= "        \$(document).ready(function() {\n";
        $content .= "            \$('#{strtolower($param)}').DataTable({\n";
        $content .= "                \"pageLength\": 50,\n";
        $content .= "                \"language\": {\n";
        $content .= "                    \"sProcessing\":     \"Procesando...\",\n";
        $content .= "                    \"sLengthMenu\":     \"Mostrar _MENU_ registros\",\n";
        $content .= "                    \"sZeroRecords\":    \"No se encontraron resultados\",\n";
        $content .= "                    \"sEmptyTable\":     \"Ningún dato disponible en esta tabla\",\n";
        $content .= "                    \"sInfo\":           \"Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros\",\n";
        $content .= "                    \"sInfoEmpty\":      \"Mostrando registros del 0 al 0 de un total de 0 registros\",\n";
        $content .= "                    \"sInfoFiltered\":   \"(filtrado de un total de _MAX_ registros)\",\n";
        $content .= "                    \"sInfoPostFix\":    \"\",\n";
        $content .= "                    \"sSearch\":         \"Buscar:\",\n";
        $content .= "                    \"sUrl\":            \"\",\n";
        $content .= "                    \"sInfoThousands\":  \",\",\n";
        $content .= "                    \"sLoadingRecords\": \"Cargando...\",\n";
        $content .= "                    \"oPaginate\": {\n";
        $content .= "                        \"sFirst\":    \"Primero\",\n";
        $content .= "                        \"sLast\":     \"Último\",\n";
        $content .= "                        \"sNext\":     \"Siguiente\",\n";
        $content .= "                        \"sPrevious\": \"Anterior\"\n";
        $content .= "                    },\n";
        $content .= "                    \"oAria\": {\n";
        $content .= "                        \"sSortAscending\":  \": Activar para ordenar la columna de manera ascendente\",\n";
        $content .= "                        \"sSortDescending\": \": Activar para ordenar la columna de manera descendente\"\n";
        $content .= "                    },\n";
        $content .= "                    \"buttons\": {\n";
        $content .= "                        \"copy\": \"Copiar\",\n";
        $content .= "                        \"colvis\": \"Visibilidad\"\n";
        $content .= "                    }\n";
        $content .= "                }\n";
        $content .= "            } );\n";
        $content .= "        } );\n";
        $content .= "    </script>\n";
        $content .= "<?php } ?>\n";

        return $content;
    }
}